### ISSUE TITLE
Training question

### ISSUE THREAD

**Issue by jdg900** [sohyun-l/fifo#1]
Thank you for sharing the code of your excellent work.

I have a question about your implementation.

Could you provide a rough estimate of how much time was required for each model to train?

I'm looking forward to hearing your reply.

Thank you.

**Comment by sohyun-l** [comment]
Thanks for your interest in our work!
We train FIFO with a single RTX 3090 GPU (24GB), and it took about 3 days.

**Comment by jdg900** [comment]
Thanks!
