### ISSUE TITLE
About train_config.py and Foggy Zurich dataset

### ISSUE THREAD

**Issue by jdg900** [sohyun-l/fifo#2]
Hi.

When I tried to implement your code according to your instruction, I encountered some issues.

In ./configs/train_config.py, DATA_LIST_RF is set to './data/Foggy_Zurich/lists_file_names/RGB_sum_filenames.txt'.

However, when I downloaded the Foggy Zurich dataset, there was no 'lists_file_names/RGB_sum_filenames.txt'.

Did you manually merge 'RGB_medium_filenames.txt' and 'RGB_light_filenames.txt' in the Foggy Zurich dataset into 'RGB_sum_filenames.txt'?

I'm looking forward to hearing your reply.

Thank you!

**Comment by sohyun-l** [comment]
Hi!

Yes, as you said, I manually merged 'RGB_medium_filenames.txt' and 'RGB_light_filenames.txt' into 'RGB_sum_filenames.txt' to utilize images with diverse real fog densities during training.

I will add the 'RGB_sum_filenames.txt' file to this repository. 

Thank you for announcing it :smile: !

**Comment by jdg900** [comment]
Thank you for your quick reply!

**Comment by cht619** [comment]
There are no labels in Foggy_Zurich-train??
