### ISSUE TITLE
Question about ACDC dataset

### ISSUE THREAD

**Issue by MYMY-young** [sohyun-l/fifo#7]
Hi, Thanks for sharing the code.

I trained the FIFO and reproduced it on FZ, FDD, FD, CW Lindau datasets.

But I'm unable to reproduce on the ACDC dataset. The performance is lower.
(fog : 51.61, rain : 46.34, night : 14.26, snow : 44.3)

I'm wondering if there are any additional changes needed to achieve the reported performance on the ACDC dataset.

Thanks.

**Comment by sohyun-l** [comment]
We report the ACDC test accuracy results for the FIFO model, which achieved the highest validation performance on the ACDC validation dataset.

**Comment by MYMY-young** [comment]
Thank you for the reply!
