### ISSUE TITLE
Frosty Cityscapes dataset

### ISSUE THREAD

**Issue by tg-Flipped** [sohyun-l/fifo#8]
Hi authors, thanks for your good work!
How could I obtain the frosty version of Cityscapes? If possible, could you share it with me. 
Looking forward to your reply. Thanks.

**Comment by sohyun-l** [comment]
Hi, thanks for your interest in our work!
We used the frost synthesizing algorithm used in ImageNet-C (https://github.com/hendrycks/robustness)
